name: json_to_form
description: A flutter plugin to use convert Json to Form Basic
version: 0.0.4
homepage: https://github.com/VictorRancesCode/json_to_form

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - example/images/

environment:
  sdk: '>=2.2.2 <3.0.0'